apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability-stack.fullname" . }}-collector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
data:
  collector.yaml: |
{{ include "observability-stack.collectorConfig" . | indent 4 }}
