// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/k8sapilog component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("k8sapilog")
	ScopeName = "github.com/eugenekurasov/security-observability-stack/otel-components/k8sapilogreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
