// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/eugenekurasov/security-observability-stack/otel-components/k8spodlogreceiver")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/eugenekurasov/security-observability-stack/otel-components/k8spodlogreceiver")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                        metric.Meter
	mu                           sync.Mutex
	registrations                []metric.Registration
	ActiveLogStreams             metric.Int64Gauge
	LogConnectionErrorsTotal     metric.Int64Counter
	LogConnectionReconnectsTotal metric.Int64Counter
	PodDiscoveryEventsTotal      metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ActiveLogStreams, err = builder.meter.Int64Gauge(
		"otelcol_active_log_streams",
		metric.WithDescription("Number of pod/container log streams currently being tailed [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.LogConnectionErrorsTotal, err = builder.meter.Int64Counter(
		"otelcol_log_connection_errors_total",
		metric.WithDescription("Number of log stream connection errors, by reason [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.LogConnectionReconnectsTotal, err = builder.meter.Int64Counter(
		"otelcol_log_connection_reconnects_total",
		metric.WithDescription("Number of times a pod/container log stream was re-established after the initial connection [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.PodDiscoveryEventsTotal, err = builder.meter.Int64Counter(
		"otelcol_pod_discovery_events_total",
		metric.WithDescription("Number of pod add/delete events observed by the discovery informer (debug) [Development]"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
