name: Lint

on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Cache vendor
        id: cache-vendor
        uses: actions/cache@v6
        with:
          path: otel-components/k8spodlogreceiver/vendor
          key: ${{ runner.os }}-go-vendor-${{ hashFiles('otel-components/k8spodlogreceiver/go.sum') }}
      - uses: actions/setup-go@v6
        with:
          go-version-file: otel-components/k8spodlogreceiver/go.mod
      - uses: golangci/golangci-lint-action@v9
        with:
          working-directory: otel-components/k8spodlogreceiver